### ISSUE TITLE
ImportError: cannot import name '_RelativePathExtension' from 'mkdocs.structure.pages'

### ISSUE THREAD

**Issue by Lucas-C** [greenape/mknotebooks#1100]
Hi,

This import is now invalid:
https://github.com/greenape/mknotebooks/blob/master/mknotebooks/plugin.py#L17

This changed in PR https://github.com/mkdocs/mkdocs/pull/3283 that was released in `mkdocs` [1.5.0](https://github.com/mkdocs/mkdocs/releases/tag/1.5.0) last week.

I have just discovered that in this GitHub Actions pipeline exection:
https://github.com/PyFPDF/fpdf2/actions/runs/5731678301/job/15533085644

**Comment by CribberSix** [comment]
Same here. Removed the plugin from our repositories for the time being.

**Comment by SoumayaMauthoorMOJ** [comment]
Same here from https://github.com/ministryofjustice/mkdocs-tech-docs-template

**Comment by greenape** [comment]
This should now be fixed.

**Comment by CribberSix** [comment]
This is great news! Thank you so much!

**Comment by Lucas-C** [comment]
Thank you @greenape, I confirm that this is now fixed for my use-case 👍
