### ISSUE TITLE
Syntax highlight?

### ISSUE THREAD

**Issue by ccamara** [greenape/mknotebooks#19]
I have just discovered this excellent plugin and I love it. I didn't manage, though, to have the code highlighted (see here in action: https://osmimports.mapcolabora.org/import_bcn_trees/)

![Screenshot_2020-03-09 Barcelona's Trees Import - OSM Imports' preparations](https://user-images.githubusercontent.com/706549/76196730-a8293f00-61e2-11ea-993d-c4182ad966c8.png)

Is there any way to achieve that?

**Comment by ccamara** [comment]
Oh, forget it... I see that I needed to install pygments and enable the extension for my theme in mkdocs. Problem solved!

![imatge](https://user-images.githubusercontent.com/706549/76197622-68fbed80-61e4-11ea-8918-782cd528a47c.png)

**Comment by greenape** [comment]
Glad you got it sorted - I’ll add mention of that to the docs.

**Comment by ccamara** [comment]
Great! I created a PR, with that, though (don't know if you wanted to do it elsewhere or differently, though)

**Comment by MasterScrat** [comment]
Hey, so I installed Pygment and mknotebooks, but I have a problem with syntax highlighting: I don't see where I should specify what language I'm using?

If I use one of the special syntax like the triple colon (eg `:::python`) or a shebang everything works fine.

But looking at @ccamara's example he doesn't seem to use either and still it works! I really don't want to have to specify the language in each cell. If there was a "default language" config that'd be fine as everything will be Python!

Demo here: https://masterscrat.github.io/rl-insights/notebooks/Title_of_the_notebook/
