### ISSUE TITLE
Inline/embedded/attached images are causing false warnings/errors

### ISSUE THREAD

**Issue by ktarplee** [greenape/mknotebooks#34]
For example a markdown cell in a notebook can have the following
```
![coco-examples.jpg](attachment:coco-examples.jpg)
```

This would refer to an attachment (coco-examples.jpg) that is included in the ipynb file.  

These can be added to any notebook by selecting the Edit Menu then "Insert Image".

If you then run `mkdocs serve`  it produces the warning

> WARNING -  Documentation file 'datasets/coco/usage.ipynb' contains a link to 'datasets/coco/coco-examples.jpg' which is not found in the documentation files.

When strict mode is turned on this is fatal.  You simply need to ignore links that have "attachment:" at the beginning to correct the issue.

**Comment by greenape** [comment]
This should be fixed as of 0.6.0
