### ISSUE TITLE
Plolty plot not showing up

### ISSUE THREAD

**Issue by Acruve15** [greenape/mknotebooks#350]
Hi! First, thanks for this awesome library that I always use when I have to create jupyter notebooks in mkdocs :) 

I am having some issues with plotly, where my plots are not rendering.

Raw code:
```
import plotly.offline as py
py.init_notebook_mode(connected=False)

import plotly.express as px
df = px.data.iris() # iris is a pandas DataFrame
fig = px.scatter(df, x="sepal_width", y="sepal_length")
fig.show(renderer="notebook") # also tested with `py.iplot(fig)`
```

Documentation Screenshot:
![image](https://user-images.githubusercontent.com/33450491/113110861-db80a680-9207-11eb-8bba-32b83c6ca21b.png)

However when I run the command `jupyter nbconvert --execute --to html my_notebook.ipynb` we do see the plot. 

Any clue why this is happening?

Many thanks in advance

## My dependencies:

Python 3.8

mkdocs==1.1.2
mkdocs-material==6.1.6
mkdocs-material-extensions==1.0.1
mkdocs-minify-plugin==0.3.0
mkdocstrings==0.13.6
mknotebooks==0.7.0
nbconvert==6.0.7
plotly==4.14.3

**Comment by YannBeauxis** [comment]
I have the same issue. 
@Acruve15  did you find a solution ?

**Comment by dacort** [comment]
Use `fig.show(renderer="jupyterlab")` - I think this is because an interactive renderer will get used by default ( see https://plotly.com/python/renderers/ ).
