### ISSUE TITLE
Add option to remove code cells

### ISSUE THREAD

**Issue by timvink** [greenape/mknotebooks#36]
For certain reports I would like to remove the code blocks, and retain only the markdown and output cells.

We can do this using the `nbconvert` configuration option `no-input` (see https://nbconvert.readthedocs.io/en/latest/config_options.html) and add an option to this plugin to enable it.

If this is a feature you are open to adding to the plugin, I'd be happy to work on a merge request, let me know.

**Comment by timvink** [comment]
Looked into this a bit more, and did not get it working immediately.

For reference, I tried the example code from https://nbconvert.readthedocs.io/en/latest/removing_cells.html

```python
exporter_config.TagRemovePreprocessor.remove_cell_tags = ("remove_cell",)
exporter_config.TagRemovePreprocessor.remove_input_tags = ('remove_input',)
exporter_config.HTMLExporter.preprocessors = ["TagRemovePreprocessor"]
```

That gave me "No module named 'TagRemovePreprocessor'".

I tried the proposed solution in [this issue](https://github.com/jupyter/nbconvert/issues/1194) to no avail. 

```python
exporter_config.TagRemovePreprocessor.remove_cell_tags = ("remove_cell",)
exporter_config.TagRemovePreprocessor.remove_input_tags = ('remove_input',)
exporter_config.TagRemovePreprocessor.enabled = True
```

So this one needs some more research

**Comment by yuanzhaoYZ** [comment]
@timvink I got it working 

```
from traitlets.config import Config
import nbformat as nbf
from nbconvert.exporters import NotebookExporter
from nbconvert.preprocessors import TagRemovePreprocessor
c = Config()

# Configure our tag removal
c.TagRemovePreprocessor.remove_cell_tags = ("remove_cell",)
c.TagRemovePreprocessor.remove_all_outputs_tags = ('remove_output',)
c.TagRemovePreprocessor.remove_input_tags = ('remove_input',)
c.TagRemovePreprocessor.enabled = True


# Configure and run out exporter
c.NotebookExporter.preprocessors = ["nbconvert.preprocessors.TagRemovePreprocessor"]

exporter = NotebookExporter(config=c)
exporter.register_preprocessor(TagRemovePreprocessor(config=c),True)

exporter.from_filename("XXXXX.ipynb")
```

**Comment by greenape** [comment]
Tag remove, nbconvert input/code etc remove, and regex remove should all be available as of 0.6.0

**Comment by timvink** [comment]
Nice! 🎉 

Still missing some documentation in the `README.md` though ;)

**Comment by pharringtonp19** [comment]
Is it possible to hide a code block but still show the output?
