### ISSUE TITLE
Terminal output with color is shown improperly

### ISSUE THREAD

**Issue by certik** [greenape/mknotebooks#4]
The escape sequences are not converted to html, but shown as is. This makes terminal output that uses colors look ugly.

**Comment by greenape** [comment]
Can you give me an example?

Behind the scenes, this plugin is just calling Jupyter to do the actual export, so might be something I can fix, might be an issue with the exporter.

**Comment by certik** [comment]
Sure, just put this into a Jupyter cell:
```
!echo "Default \e[32mGreen"
```

I investigated the situation and what happens is that you use a Markdown exporter, which simply leaves those ansi escape codes intact. The HTML exporter, on the other hand, uses the following template:

https://github.com/jupyter/nbconvert/blob/b625b1036b04825cf372d4568450cdd40fea77a0/nbconvert/templates/html/basic.tpl#L105

which at the indicated line uses the `ansi2html` filter, defined here:

https://github.com/jupyter/nbconvert/blob/b625b1036b04825cf372d4568450cdd40fea77a0/nbconvert/filters/ansi.py#L50

it simply calls the `_ansi2anything` function:

https://github.com/jupyter/nbconvert/blob/b625b1036b04825cf372d4568450cdd40fea77a0/nbconvert/filters/ansi.py#L171

which does the actual conversion.


Conclusion: The live notebook, as well as the HTML conversion correctly converts the terminal ansi codes, but the Markdown converter leaves them intact.

How to fix it? Well, I think first we need to identify the cells that should be run through this `ansi2html` filter, and make Markdown converter output something like this:

    ```ansi
    Default \e[32mGreen
    ```

Then we need to write an extension to `python-markdown` to format this special `ansi` fenced block using the `ansi2html` filter.

I think that would be the cleanest solution.

**Comment by certik** [comment]
Figured it out.

Here is a notebook:

https://gitlab.com/lfortran/lfortran/blob/882626f0d7db41c9039e979308335c207df4592a/doc/nb/developer_tutorial.ipynb

Here is how it is converted to Markdown:

https://gitlab.com/lfortran/lfortran/blob/882626f0d7db41c9039e979308335c207df4592a/doc/convert_nb.py

And here is how it looks like:

https://docs.lfortran.org/developer_tutorial/

The terminal output is presented correctly in colors, as you can see.

The only problem with my approach is that the "Edit on GitLab" link in mkdocs now links to a non-existent md file, since I do not track the generated md file in git. One solution would be to integrate it with your package.

However, for debugging reasons, I really like that I can look at the generated Markdown file. Is there an option in your package to show the generated Markdown?

**Comment by greenape** [comment]
Just pushed a change which lets you dump the generated markdown as well.

**Comment by greenape** [comment]
This should be fixed now.
