### ISSUE TITLE
Add a "binder" link configuration option?

### ISSUE THREAD

**Issue by ericmjl** [greenape/mknotebooks#43]
Hello @greenape! I love `mknotebooks`, and I have used it as part of the [Network Analysis Made Simple](https://ericmjl.github.io/Network-Analysis-Made-Simple/) tutorial series (in concert with `mkdocs-material`). Thanks for putting `mknotebooks` out there!

I was wondering if you might be open to an idea? The idea I have is to add a "launch binder" Markdown cell at the top of a notebook, such that the binder link would bring a reader of the notebook directly to a Binder session with the notebook opened up. Such a link would look like this:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/2631566/93005652-f831e700-f520-11ea-863a-dc0288d6c2d4.png">

You can see a live demo of the idea [here](https://ericmjl.github.io/Network-Analysis-Made-Simple/01-introduction/03-viz/). Notice how this doesn't merely open up a Binder session where all notebooks are accessible; the link goes one step further and directly opens up the `01-introduction/03-viz.ipynb` notebook, not unlike directly opening up a notebook in Colab.

Right now, I had to do a bit of a hack, in which I first manually added a cell at the top of each notebook, and then ran `mkdocs build`. I was thinking that maybe adding a config under the `plugins` section would be the right way to go. This would look like:

```yaml
plugins:
  - mknotebooks:
      execute: true
      write_markdown: true
      allow_errors: true
      timeout: 1200
      binder:
        notebook_links: true
        repo_name: ericmjl/Network-Analysis-Made-Simple  # in the form username/reponame
```

As far as I can tell, `repo_name` is the only thing that _might_ need to be configured -- it actually can be taken from the overall MkDocs config (the `repo_name` key). 

The construction of the Binder badge is quite simple as well:

```
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/<REPO_NAME>/master?filepath=<FILEPATH>)
```

`<FILEPATH>` can be constructed by taking appending to `docs`:

```python
notebook_relpath = ... # parse from mkdocs.yml config
nbpath = Path("docs") / notebook_relpath
FILEPATH = str(nbpath).replace("/", "%2F")
```

Initially, I'd suggest support for just the GitHub URLs, and with further expansion based on user requests and PRs sent in.

The problem I'm facing though is that I'm not quite sure where in the `plugin.py` I might need to modify. I was thinking maybe I'd have to modify `on_page_read_source`, since the `config` object (which I'm assuming is the mkdocs config object?) is referenced in there. Would that be the right starting point? Please let me know!

**Comment by ericmjl** [comment]
Update: on a branch on my fork, I have this working! :smile:

![image](https://user-images.githubusercontent.com/2631566/93007997-9e8be580-f53d-11ea-87ae-3ac6f1b8f6e3.png)

**Comment by greenape** [comment]
Awesome idea!
