### ISSUE TITLE
Search bar missing on notebook pages

### ISSUE THREAD

**Issue by rclement** [greenape/mknotebooks#519]
## Description

When using `mknotebooks` combined with the `search` plugin, the search bar is either disabled (default theme) or completely missing (`mkdocs-material` theme) but only for notebook pages.

This behavior can be observed with any of the examples by activating the `search` plugin:

<img width="1195" alt="Screenshot 2021-08-12 at 18 20 54" src="https://user-images.githubusercontent.com/1238873/129233012-9b669279-a8e7-4897-9d8b-cc78b768d153.png">

<img width="1228" alt="Screenshot 2021-08-12 at 18 20 35" src="https://user-images.githubusercontent.com/1238873/129233038-32f4f423-5cce-4942-a7e8-87dcbcfaaf43.png">

## Observations

The search bar is enabled at runtime by some JavaScript code provided by the theme: when doing so, the `.no-js` class should be dynamically removed from the top-level HTML tag:

```html
<!doctype html>
<html lang="en" class="no-js">
  <head>
...
```

For notebook pages, this class is not dynamically removed from the DOM. Trying to remove it by hand (to simulate the behavior) makes the search bar appear but without any JavaScript interaction.

It seems **some JS code specific to notebooks is inhibiting the JS code of the theme**.
This can be observe in two places:

- The Git repository information (top-right corner) is not fetch at runtime (no stars, etc.)
- The browser devtools console showing error when loading JS code from `mkdocs-material`:

<img width="1434" alt="Screenshot 2021-08-12 at 18 38 36" src="https://user-images.githubusercontent.com/1238873/129234842-b0198025-427a-4270-84f3-cdd9f8a6796e.png">

Digging a bit further, only deactivating [this JavaScript include](https://github.com/greenape/mknotebooks/blob/e5affa0cb7ae78ee9f13237a84d94cc8fd60e889/mknotebooks/templates/custom_markdown.tpl#L6) makes the whole search bar system appear and work:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js"></script>
```

## Hypothesis

The inclusion of the `require.js` library seems definitely involved in the culprit.

I do not know the root cause of all this but some a report has been make and fixed in `mkdocs-material`: https://github.com/squidfunk/mkdocs-material/issues/2339

I will be happy to do some more testing and/or provided some feedback!

**Comment by rclement** [comment]
It seems other MkDocs plugins using JS code are disabled when used on notebook pages.
For instance, with `mkdocs-git-revision-date-localized-plugin`: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/40

**Comment by akhmerov** [comment]
It seems that requirejs (including its latest version) for an unknown reason interferes with `rxjs`.

A possible and an extremely ugly workaround would be to move also the bundle to load before require (so to the page header).

**Comment by timvink** [comment]
Good find, hope we can fix this :)

**Comment by rclement** [comment]
I may have found a workaround: instead of including `require.js` at the end of the page content, appending at the end of the body with `@jupyter-widgets` works on a few examples. PR #565 submitted with this fix.

Here is one of the examples of this repo working after using the fix (no more JS errors, search bar is working again):

<img width="1203" alt="Screenshot 2021-09-03 at 23 14 06" src="https://user-images.githubusercontent.com/1238873/132066929-1b22fb66-9c90-4afe-8e88-8862f06c8d4b.png">

**Comment by rclement** [comment]
I'll close the issue for now as a fix has been merged on master branch. Feel free to reopen the issue if needed.
