### ISSUE TITLE
Latex in cell output or markdown fields does not render

### ISSUE THREAD

**Issue by mniehus** [greenape/mknotebooks#586]
I find that Latex in cell output or markdown fields does not render. Is this some known issue? Are there examples where it does render? 
thank You, cheers

**Comment by rclement** [comment]
You do have to enable Mathjax rendering on your MkDocs Theme.

For instance using Mkdocs-Material theme: https://squidfunk.github.io/mkdocs-material/reference/mathjax/

**Comment by mniehus** [comment]
i did actually follow those steps, and several other things. 
I did now solve the preoblem, and Your response was fundamental to brng me on the right track. 
within the mkdocs framework, the latex rendering of markdowns was actually working perfectly, just the equivalent rendering in jupyternotebooks within mknotebook not. it worked within the jupyter markdown cells and jupyter output cells only for the single dollar sign, but not for the double dollar sign. i now found an example online where it is actually working, nasa's kamodo project (https://github.com/nasa/Kamodo) . In their  mkdocs.yml file, they use a different link for extra_javascripts: instead of   " - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" as in https://squidfunk.github.io/mkdocs-material/reference/mathjax/ they used " - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML" cf. https://github.com/nasa/Kamodo/blob/master/mkdocs.yml. 
Changing the  extra_javascripts pointer in the mkdocs.yml to  " - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML" resolved this for me. My jupyter notebook are now nicely rendering. 
i just have to figure out how to activate and bind them, but this is for another post. 
Thank You very much !

**Comment by rclement** [comment]
Ok great if you solved your issue!

FYI, so far I have always used the configuration given by mkdocs-material documentation and it has always worked with both markdown and notebooks pages, either with inline (`$...$`) or block (`$$ .... $$`) math equation.

**Comment by greenape** [comment]
Glad you found a solution :)
