### ISSUE TITLE
Image parsing failed

### ISSUE THREAD

**Issue by lanking520** [greenape/mknotebooks#90]
after upgrade to 0.6.1 with latest nbconvert. It seemed the image parsing has failed:

http://docs.djl.ai/jupyter/load_mxnet_model.html

This is a generated html where you can see some image below are displayed incorrectly.

You can try to run online through clicking the button above and image seemed rendered fine in the notebook itself.

**Comment by greenape** [comment]
Looks like the tag is getting escaped, I'll jiggle the template around again. 👍

**Comment by lanking520** [comment]
It crashed my search engine to grab for search. Getting back to previous version also didn't help much. Here is my current workaround:

```
nbconvert==5.6.1 mkdocs mkdocs-exclude mknotebooks==0.4.1 mkdocs-material jupyter Pygments Markdown==3.2.2
```

This combination temporaily work for now. But I guess things might break sooner if jupyter and other packages has an update

**Comment by lanking520** [comment]
Since the nbconvert update very fast (they iterate 5 minor versions in the past month), I would recommend mknotebooks to stick on a certain version of it

**Comment by greenape** [comment]
Argh. Yeah, there were substantial changes in the last midpoint releases of nbconvert and markdown which are combining to make this all a bit awkward. Ideally I'd like to avoid pinning to specific versions, but it may be necessary if I can't work out what's going on/keep up with the changes to the nbconvert templating and markdown's parsing.

**Comment by greenape** [comment]
Ok - looks like https://github.com/Python-Markdown/markdown/pull/1044 will fix this, plus several other parsing issues. Once there's a release of markdown which incorporates it, I'll repin and make any tweaks to the template necessary to get things back in order.

**Comment by lanking520** [comment]
@greenape Thanks, will try today
